---
driver: docker
driver_config:
  privileged: true
  socket: <%= ENV['DOCKER_HOST'] %>

platforms:
  - name: ubuntu-12.04
    driver_config:
      provision_command:
        - apt-get install -y net-tools
  - name: ubuntu-14.04
    driver_config:
      provision_command:
        - apt-get install -y net-tools
  - name: debian-7.4
    driver_config:
      provision_command:
        - apt-get install -y net-tools
  - name: centos-6

suites:
  - name: backend-pam
    run_list:
      - recipe[pure-ftpd::default]
    attributes:
      pure-ftpd:
        backend: 'pam'
  - name: backend-unix
    run_list:
      - recipe[pure-ftpd::default]
    attributes:
      pure-ftpd:
        backend: 'unix'
  - name: backend-mysql
    run_list:
      - recipe[pure-ftpd::default]
    attributes:
      pure-ftpd:
        backend: 'mysql'
        mysql:
          user: 'root'
          password: 'rootpw'
  - name: backend-postgresql
    run_list:
      - recipe[pure-ftpd::default]
    attributes:
      pure-ftpd:
        backend: 'postgresql'
        postgresql:
          user: 'root'
          password: 'rootpw'
