language: ruby
sudo: false
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.9
bundler_args: --without "kitchen_vagrant kitchen_common" --jobs 4
script:
  - bundle exec foodcritic .
  - bundle exec rubocop
  - bundle exec rspec
